# Os Fungos do Bosque  Resumo Detalhado

| PortuguÃªs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | English                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **DescriÃ§Ã£o:** Aventureiros recÃ©m-chegados ao mundo de Greyhawk, acordam no Grande Castelo e reÃºnem-se na taberna RefÃºgio do Errante, onde recebem do taberneiro a missÃ£o de investigar uma infestaÃ§Ã£o de fungos alienÃ­genas num bosque prÃ³ximo. Guiados pelo antigo treant Borogrove, entram numa caverna infestada, enfrentam criaturas mutantes (Twig Blights, Bullywugs, Urso corrompido) e confrontam um druida infetado. ApÃ³s purificar a nascente do riacho, regressam ao refÃºgio, onde recebem recompensas e alguns, curiosamente, experimentam cogumelos mesmo apÃ³s a experiÃªncia traumÃ¡tica. | **Description:** Adventurers newly arrived in the world of Greyhawk awaken in the Great Castle and gather at the Refuge of the Wanderer tavern, where the innkeeper tasks them with investigating an alien fungus infestation in a nearby forest. Guided by the ancient treant Borogrove, they enter an infested cave, face mutant creatures (Twig Blights, Bullywugs, corrupted Bear), and confront an infected druid. After purifying the streams source, they return to the refuge, receiving rewardsand some, oddly, eat mushrooms even after the ordeal. |
| **NPCs:** Major-domo do Castelo, Taverneiro do RefÃºgio, Borogrove, Druida Infetado                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **NPCs:** Castle Majordomo, Refuge Innkeeper, Borogrove, Infected Druid                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Loot:** Staff of Flowers, ouro, gemas, faca de prata, bolota mÃ¡gica, Livro do Druida Infetado                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **Loot:** Staff of Flowers, gold, gems, silver knife, magic acorn, Infected Druids Book                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| **Data:** 2025-01-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     | **Date:** 2025-01-02                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
| **Ficheiros de origem:** s01_-_2025-01-02.md, s01_os_fungos_do_bosque_resumo.md                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | **Source files:** s01_-_2025-01-02.md, s01_os_fungos_do_bosque_resumo.md                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |

























