# Sarvian Midlor

![[pc_sarvian_midlor.png]]

| PortuguÃªs                                                                                                                           | English                                                                                                                          |
| ----------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------- |
| **Jogador:** Hugo AlcÃ¢ntara                                                                                                         | **Player:** Hugo AlcÃ¢ntara                                                                                                       |
| **Idade:** 28 anos                                                                                                                  | **Age:** 28 years                                                                                                                |
| **Tamanho:** MÃ©dio (1,70 m)                                                                                                         | **Size:** Medium (1.70 m)                                                                                                        |
| **GÃ©nero:** NÃ£o-binÃ¡rio (elu/delu)                                                                                                  | **Gender:** Non-binary (they/them)                                                                                               |
| **RaÃ§a:** TritÃ£o                                                                                                                    | **Race:** Triton                                                                                                                 |
| **Classe:** Bardo                                                                                                                   | **Class:** Bard                                                                                                                  |
| **Alinhamento:** Neutro e Bom                                                                                                       | **Alignment:** Neutral Good                                                                                                      |
| **Ficha D&D Beyond:** [Link](https://www.dndbeyond.com/characters/140181540)                                                        | **D&D Beyond Sheet:** [Link](https://www.dndbeyond.com/characters/140181540)                                                     |
| **SessÃµes jogadas:** 0                                                                                                              | **Sessions played:** 0                                                                                                           |
| **Contacto:** +351 927 401 274                                                                                                      | **Contact:** +351 927 401 274                                                                                                    |

| PortuguÃªs                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | English                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **DescriÃ§Ã£o:** Costureiro e aventureiro, recebe o anel mÃ¡gico de Zorg durante o baile e envolve-se em missÃµes de espionagem social. | **Description:** Tailor and adventurer, receives Zorgs magic ring at the ball and becomes involved in social espionage missions. |
| **TraÃ§os de Personalidade:** Extravagante, comenta sempre sobre a roupa e aparÃªncia das pessoas. Oferece os seus serviÃ§os quando pode  afinal, Ã© o melhor! Preocupa-se com os outros e nÃ£o suporta injustiÃ§as.                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | **Personality Traits:** Flamboyant, always commenting on people's clothing and looks. Offers their services when they can  after all, they are the best! Cares for people and cannot stand injustice.                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| **Ideais:** Procura a seda mais elegante, vestir apenas o melhor e produzir apenas o melhor. Coleciona peÃ§as que possa transformar em algo novo. A verdadeira razÃ£o da sua jornada Ã© encontrar uma cura para a doenÃ§a da irmÃ£, Kilmy. Nunca perderÃ¡ a esperanÃ§a nem a abandonarÃ¡, enviando para casa todo o ouro que possa dispensar.                                                                                                                                                                                                                                                                                                                                            | **Ideals:** They want to find the most elegant silks, wear only the best, and produce only the best. They collect pieces they can transform into something new. The true reason for their journey is to find a cure for their sister Kilmys disease. They will never abandon hope or her, sending home any gold they can spare.                                                                                                                                                                                                                                                                                                                                 |
| **LigaÃ§Ãµes:** Apesar de viajar constantemente e vender as suas roupas em vÃ¡rias regiÃµes, pensa sempre na irmÃ£ Kilmy. O pai esteve sempre ausente e a mÃ£e, Joll Midlor, faz o que pode para cuidar de Kilmy.                                                                                                                                                                                                                                                                                                                                                                                                                                                                      | **Bonds:** Despite travelling constantly and selling their clothes across many regions, they always think of their sister Kilmy. Their father was always absent and their mother, Joll Midlor, does what she can to care for Kilmy.                                                                                                                                                                                                                                                                                                                                                                                                                              |
| **Defeitos:** Muitas vezes sÃ£o vistos como narcisistas e desinteressados, dizem a coisa errada no momento errado. IngÃ©nuos nos hÃ¡bitos da superfÃ­cie.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            | **Flaws:** Often seen as narcissistic and uncaring, they have a knack for saying the wrong thing at the wrong time. NaÃ¯ve to surface habits.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| **HistÃ³ria:** Nascido nas profundezas do mar Oljatt, Sarvian era uma crianÃ§a caÃ³tica, sempre Ã  procura de aventura. Aos 15 anos, encontrou restos do mundo da superfÃ­cie  tecidos e roupas de cores vibrantes. Com a mÃ£e, abriu a primeira loja de moda das profundezas, mas a felicidade terminou quando Kilmy adoeceu misteriosamente. Determinado a salvÃ¡-la, Sarvian aventurou-se em terra firme, prosperando como estilista e aprendendo que a arte podia ser mÃ¡gica. Tornou-se aprendiz do comerciante Vrith Boralis, que mais tarde o traiu e matou por informaÃ§Ã£o sobre um mÃ©todo mÃ¡gico de transformar coral em tecido. Contudo, Sarvian acordou vivo, sem saber como. | **Backstory:** Born in the depths of the Oljatt Sea, Sarvian was a chaotic child always seeking adventure. At 15, they found remnants of the surface world  fabrics and clothes with vibrant colors. Together with their mother, they opened the first fashion shop in the depths, but happiness ended when Kilmy mysteriously fell ill. Determined to save her, Sarvian ventured onto dry land, thriving as a stylist and learning that art could be magical. They became apprentice to merchant Vrith Boralis, who later betrayed and killed them for information on a magical method of turning coral into fabric. Yet Sarvian awoke alive, not knowing how. |
| **AtualizaÃ§Ãµes:** Encontrou versÃµes de si no passado e no futuro; foi drogado por Trixie e pode ter engravidado; descobriu que a irmÃ£ estÃ¡ saudÃ¡vel e Ã© capitÃ£ dos piratas Rosa Negra, levantando novas perguntas.                                                                                                                                                                                                                                                                                                                                                                                                                                                               | **Updates:** Met past and future versions of themselves; was drugged by Trixie and may have impregnated her; discovered their sister is healthy and captain of the Rosa Negra pirates, raising new questions.                                                                                                                                                                                                                                                                                                                                                                                                                                                    |







