name: Deploy MkDocs to OCI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy site with rsync
        uses: burnett01/rsync-deployments@v1
        with:
          switches: -avz --delete
          path: site/
          remote_path: /var/www/bardos/
          remote_host: ${{ secrets.OCI_HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.OCI_SSH_KEY }}
