name: Deploy MkDocs to OCI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocs-awesome-pages-plugin mkdocs-section-index mkdocs-gen-files

      - name: Build MkDocs
        run: mkdocs build

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.OCI_HOST }} >> ~/.ssh/known_hosts

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Check rsync path and version
        run: |
          which rsync
          echo $PATH
          rsync --version

      - name: Deploy site with rsync
        run: |
          /usr/bin/rsync -avz --delete --rsync-path=/usr/bin/rsync site/ ubuntu@${{ secrets.OCI_HOST }}:/var/www/bardos/
