name: Test Secrets Access

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check OCI_HOST secret
        env:
          OCI_HOST: ${{ secrets.OCI_HOST }}
        run: echo "OCI_HOST is set"

      - name: Check OCI_SSH_KEY secret presence
        run: |
          if [ -n "${{ secrets.OCI_SSH_KEY }}" ]; then
            echo "OCI_SSH_KEY is set"
          else
            echo "OCI_SSH_KEY is NOT set"
            exit 1
          fi
