name: Deploy MkDocs to OCI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'                 # speeds up installs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          mkdocs --version

      # Your nav generator (kept)
      - name: Generate nav menu
        run: python scripts/gen_nav.py

      - name: Build MkDocs
        run: mkdocs build # add --strict if you want failures on broken links

      # --- SSH setup + sanity check ---
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.OCI_SSH_KEY }}

      - name: Trust host key + sanity ping
        shell: bash
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan -H "${{ secrets.OCI_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          ssh -o IdentitiesOnly=yes -o BatchMode=yes -o ConnectTimeout=10 \
              ubuntu@${{ secrets.OCI_HOST }} "echo ok && uname -a"

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Deploy site with rsync
        shell: bash
        run: |
          RSYNC_SSH='ssh -o IdentitiesOnly=yes -o BatchMode=yes -o ConnectTimeout=15'
          rsync -az --delete \
            -e "$RSYNC_SSH" \
            --rsync-path=/usr/bin/rsync \
            site/ ubuntu@${{ secrets.OCI_HOST }}:/var/www/bardos/

      # Optional: verbose retry to capture SSH debug if deploy fails
      - name: Debug rsync/ssh (verbose)
        if: failure()
        run: |
          RSYNC_SSH='ssh -vvv -o IdentitiesOnly=yes -o BatchMode=yes -o ConnectTimeout=15'
          rsync -az --delete -e "$RSYNC_SSH" site/ ubuntu@${{ secrets.OCI_HOST }}:/var/www/bardos/
